apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-home-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vsftpd-helm.name" . }}
    helm.sh/chart: {{ include "vsftpd-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.home.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.home.size }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-logs-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vsftpd-helm.name" . }}
    helm.sh/chart: {{ include "vsftpd-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.logs.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}

