apiVersion: v1
kind: Service
metadata:
  name: {{ include "vsftpd-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vsftpd-helm.name" . }}
    helm.sh/chart: {{ include "vsftpd-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "vsftpd-helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: ftp-command
      port: {{ .Values.ftp.controlPort }}
      targetPort: {{ .Values.ftp.controlPort }}
      nodePort: {{ .Values.service.nodePortCommand }}
    - name: ftp-data
      port: {{ .Values.ftp.dataPort }}
      targetPort: {{ .Values.ftp.dataPort }}
      nodePort: {{ .Values.service.nodePortData }}
    {{- $baseNodePort := int .Values.service.nodePortPassiveMin }}
    {{- $pasvMinPort := int .Values.ftp.pasvMinPort }}
    {{- $pasvMaxPort := int .Values.ftp.pasvMaxPort }}
    {{- range $i, $port := untilStep $pasvMinPort (int (add1 $pasvMaxPort)) 1 }}
    - name: pasv-{{ $port }}
      port: {{ $port }}
      targetPort: {{ $port }}
      nodePort: {{ add $baseNodePort $i }}
    {{- end }}

